name: Ilk pipeline

#trigger (tetikleyici)
on:
  push: 
    branches: [ "main" ]


jobs:
  docker-login:
    name: Login to docker
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

#Docker hub a login ol.
#Not: eger repository olarak docker hub kullanilacaksa repository ismi belirtilmez

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USER }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}

      - name: Build with Maven and Push the Google Artifact Repository
        run: |
            mvn compile com.google.cloud.tools:jib-maven-plugin:3.3.1:build \
            -Dspring-boot.run.profiles=prod \
            -Dimage="sisik1967/jhipster05:latest"
